-- AlterEnum
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ORG_OWNER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ORG_MANAGER';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ORG_FINANCE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'ORG_AUDITOR';
